package:
  name: hpc05
  version: "1.8"

source:
  git_rev: v1.8
  git_url: https://github.com/basnijholt/hpc05.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: https://github.com/basnijholt/hpc05
  license: MIT


