package:
  name: hpc05
  version: "1.5"

source:
  git_rev: v1.5
  git_url: https://github.com/basnijholt/hpc05.git

build:
  number: 1

requirements:
  build:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: https://github.com/basnijholt/hpc05
  license: MIT


