package:
  name: mumps_seq
  version: 5.0.1

source:
  fn: MUMPS_5.0.1.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_5.0.1.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - gcc
    - metis
    - scotch
    - openblas [linux]

  run:
    - libgcc
    - metis
    - scotch
    - openblas [linux]

about:
  home: http://mumps.enseeiht.fr/
  license: Public domain
