package:
  name: mumps
  version: 5.0.1

source:
  fn: MUMPS_5.0.1.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_5.0.1.tar.gz

build:
  number: 5
  binary_relocation: true

requirements:
  build:
    - gcc [osx]
    - gcc ==4.9.2 [linux] 
    - libgfortran
    - metis
    - scotch

  run:
    - gcc [osx]
    - gcc ==4.9.2 [linux]
    - libgfortran
    - metis
    - scotch

about:
  home: http://mumps.enseeiht.fr/
  license: Public domain
