build:
  entry_points: []
  features: []
  number: 1
  string: ''
  track_features: []
package: {name: scotch, version: 6.0.4}
requirements:
  build:
    - gcc
  conflicts: []
  run:
    - gcc
source:
  fn: metis-4.0.3.tar.gz
  git_branch: ''
  git_tag: ''
  patches: []
  svn_rev: ''
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
test:
  commands: []
  files: []
  imports: []
  requires: []
