about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis
  license: GPLv3

package:
  name: metis
  version: 5.1.0

source:
  fn: metis-5.1.0.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - gcc
    - cmake
  run:
    - gcc
    - cmake
