package:
  name: mumps
  version: 5.0.1

source:
  fn: MUMPS_5.0.1.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_5.0.1.tar.gz

build:
  number: 2

requirements:
  build:
    - metis
    - scotch

  run:
    - libgcc
    - metis
    - scotch

about:
  home: http://mumps.enseeiht.fr/
  license: Public domain
