package:
  name: scotch
  version: 6.0.0

requirements:
 build:
  - gcc
 run:
  - gcc

source:
  fn: scotch_6.0.0_esmumps.tar.gz
  md5: c50d6187462ba801f9a82133ee666e8e
  url: http://gforge.inria.fr/frs/download.php/file/31832/scotch_6.0.0_esmumps.tar.gz
  patches:
    - clock_gettime.patch [osx]
