package:
  name: scotch
  version: 6.0.4

requirements:
 build:
  - gcc
  - zlib
 run:
  - zlib
  - libgcc

build:
  number: 1

source:
  fn: scotch_6.0.4.tar.gz
  md5: d58b825eb95e1db77efe8c6ff42d329f
  url: http://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
  patches:
    - clock_gettime.patch [osx]
