about: {home: 'http://gforge.inria.fr/frs/download.php/file/34618/', license: CeCILL-C}
build:
  entry_points: []
  features: []
  number: 1
  string: ''
  track_features: []
package: {name: scotch, version: 6.0.4}
requirements:
  build:
    - gcc ==4.9.2 [linux]
    - gcc
  conflicts: []
  run:
    - gcc ==4.9.2 [linux]
    - gcc
source:
  fn: scotch_6.0.4.tar.gz
  git_branch: ''
  git_tag: ''
  md5: d58b825eb95e1db77efe8c6ff42d329f
  patches: []
    - clock_gettime.patch [osx]
  svn_rev: ''
  url: http://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
test:
  commands: []
  files: []
  imports: []
  requires: []
