package:
  name: kwant
  version: "1.0.4"

source:
  fn: kwant-1.0.4.tar.gz
  url: https://pypi.python.org/packages/source/k/kwant/kwant-1.0.4.tar.gz
  md5: 78c7c84c2d5fde2f8f24212b00447b78

requirements:
  build:
    - python
    - tinyarray
    - numpy
    - matplotlib
    - mumps
    - scipy
    - cython
    - nose
    - gcc [osx]
    - gcc ==4.9.2 [linux]
    - openblas
    - libgfortran

  run:
    - python
    - tinyarray
    - numpy
    - matplotlib
    - mumps
    - scipy
    - cython
    - nose
    - gcc [osx]
    - gcc ==4.9.2 [linux]
    - openblas
    - libgfortran

test:
  # Python imports
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://kwant-project.org/
  license: BSD
  summary: 'Package for numerical quantum transport calculations.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
