package:
  name: kwant
  version: "1.2.2"

source:
  git_url: https://github.com/kwant-project/kwant.git
  git_tag: v1.2.2

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - python
    - gcc
    - openblas
    - lapack
    - metis
    - scotch5
    - mumps_seq
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose
    - tinyarray
    - git

  run:
    - python
    - metis
    - scotch5
    - mumps_seq
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose
    - tinyarray
    - gcc
    - git

test:
  # Python imports
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests


about:
  home: http://kwant-project.org/
  license: BSD
  summary: 'Package for numerical quantum transport calculations.'
