package:
  name: kwant
  version: "1.2.2" [py3k]
  version: "1.1.2" [py27]

source:
  git_url: https://github.com/kwant-project/kwant.git
  git_tag: v1.2.2 [py3k]
  git_tag: v1.1.2 [py27]

build:
  number: 2
  binary_relocation: true

requirements:
  build:
    - python
    - gcc
    - openblas [linux]
    - metis
    - scotch
    - mumps_seq
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose
    - tinyarray

  run:
    - python
    - metis
    - scotch
    - openblas [linux]
    - mumps_seq
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose
    - tinyarray
    - libgcc
    - libgfortran ==1 [linux]

test:
  # Python imports
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests


about:
  home: http://kwant-project.org/
  license: BSD
  summary: 'Package for numerical quantum transport calculations.'
