package:
  name: tinyarray
  version: "1.1.0"

source:
  fn: tinyarray-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/t/tinyarray/tinyarray-1.1.0.tar.gz
  md5: 3079f1dc3648f9060518765362360d7e

requirements:
  build:
    - python
    - setuptools
    - nose
    - gcc

  run:
    - python
    - nose

about:
  home: http://git.kwant-project.org/tinyarray/about/
  license: BSD License
  summary: 'Arrays of numbers for Python, optimized for small sizes'

build:
  number: 4
