package:
  name: tinyarray
  version: "1.1.0"

source:
  fn: tinyarray-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/t/tinyarray/tinyarray-1.1.0.tar.gz
  md5: 3079f1dc3648f9060518765362360d7e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tinyarray = tinyarray:main
    #
    # Would create an entry point called tinyarray that calls tinyarray.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose

  run:
    - python
    - nose

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://git.kwant-project.org/tinyarray/about/
  license: BSD License
  summary: 'Arrays of numbers for Python, optimized for small sizes'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
