package:
  name: discretizer
  version: "0.2"

source:
  git_rev: v0.2
  git_url: git@gitlab.kwant-project.org:r-j-skolasinski/discretizer.git

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - sympy
    - numpy
  run:
    - python
    - sympy
    - kwant
    - numpy

test:
  imports:
    - discretizer

about:
  home: https://gitlab.kwant-project.org/r-j-skolasinski/discretizer
  license: BSD
