package:
  name: kwant
  version: "1.2.2"

source:
  git_url: https://github.com/kwant-project/kwant.git
  git_tag: v1.2.2

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - cython
    - nose

test:
  # Python imports
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://kwant-project.org/
  license: BSD
  summary: 'Package for numerical quantum transport calculations.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
