package:
  name: scotch5
  version: 5.1.12b

requirements:
 build:
  - gcc
 run:
  - libgcc

build:
  number: 4

source:
  fn: scotch_5.1.12b_esmumps.tar.gz
  md5: e13b49be804755470b159d7052764dc0
  url: https://gforge.inria.fr/frs/download.php/file/28978/scotch_5.1.12b_esmumps.tar.gz
  patches:
    - clock_gettime.patch [osx]
