about: {home: 'http://glaros.dtc.umn.edu/gkhome/metis/metis', license: GPLv3}
build:
  entry_points: []
  features: []
  string: ''
  track_features: []
package: {name: metis, version: 5.1.0}
requirements:
  build: []
  conflicts: []
  run: []
source:
  git_rev: ''
  md5: ''
  patches: []
  path: ''
  svn_rev: ''
test:
  commands: []
  files: []
  imports: []
  requires: []
